name: worker

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: git clone
        run: git clone https://github.com/zoglobek/tests.git

      - name: check files
        run: ls -la tests

      - name: pwd
        run: pwd

      - name: my ip
        run: curl ifconfig.me

      - name: install pip
        run: sudo apt-get install python3-pip

      - name: install dependencies
        run: pip3 install -r tests/requirements.txt

      - name: run test
        run: python3 tests/helloworld.py
